version: "3.5"
services:

  ssoweb:
    build:
      context: .
    command: /app/docker-compose/scripts/docker_compose_run.sh
    # Temporarily replace the command above with this if you want the container to just stay open 
    # so you can connect and troubleshoot b/c the container exits when you bring it up.
    #tty: true
    ports:
      - "3002:3002"
    # Make changes done outside the container reflect inside the container without needing a rebuild by mounting a volume.
    volumes:
      - .:/app
    networks:
      - bravendev
    depends_on:
      - ssodb
    environment:
      RACK_ENV: development
      DATABASE_NAME: casserver
      DATABASE_USER: postgres
      DATABASE_PASSWORD:
      DATABASE_HOST: ssodb

  ssodb:
    image: postgres:9.3
    volumes:
      - sso-db:/var/lib/postgresql/data
    networks:
      - bravendev
    environment:
      POSTGRES_DB: casserver

# Note all Braven web app docker dev envs use this same network so they can talk to each other.
# E.g. the hostname joinweb will resolve inside the ssoweb container if they are on the same docker network.
networks:
  bravendev:
    name: braven_dev_network

volumes:
  sso-db:
