version: "3"
services:

  ssoweb:
    build:
      context: .
    command: /app/docker-compose/scripts/docker_compose_run.sh
    ports:
      - "3002:3002"
    networks:
      - frontend
      - beyondz-platform_frontend
    depends_on:
      - ssodb
    environment:
      RACK_ENV: development
      DATABASE_NAME: casserver
      DATABASE_USER: postgres
      DATABASE_PASSWORD:
      DATABASE_HOST: ssodb

  ssodb:
    image: postgres:9.3
    volumes:
      - sso-db:/var/lib/postgresql/data
    networks:
      - frontend
    environment:
      POSTGRES_DB: casserver

networks:
  frontend:
  beyondz-platform_frontend:
    external: true

volumes:
  sso-db:
